platform :ios, '9.0'

target 'FMCategoryKitExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'FMCategoryKit', :path => './../'

end
